- name: Enable DMS
  ansible.builtin.systemd_service:
    name: dms.service
    scope: user
    enabled: true

- name: Enable Vicinae
  ansible.builtin.systemd_service:
    name: vicinae.service
    scope: user
    enabled: true
