#!/usr/bin/env fish

if not type -fq dnf
  exit 0
end

set -l undesired_packages \
  alacritty \
  brave-browser \
  dnf-app-center \
  libreoffice \
  libreoffice-base \
  libreoffice-calc \
  libreoffice-draw \
  libreoffice-emailmerge \
  libreoffice-impress \
  libreoffice-math \
  libreoffice-writer

function package_is_installed -a name
  rpm -q $name > /dev/null
end

for package in $undesired_packages
  if package_is_installed $package
    set -a packages_to_remove $package
  end
end

if set -q packages_to_remove[1]
  sudo dnf remove -y $packages_to_remove
end
