#!/usr/bin/env fish

status build-info | string match -q '*apple*'
  or exit 0

# Dark mode
defaults write -g AppleInterfaceStyle -string Dark

# Show folders before files in Finder
defaults write com.apple.finder _FXSortFoldersFirst -bool "true"
