#!/usr/bin/env fish

status build-info | string match -q '*apple*'
  or exit 0

# Install Homebrew if it isn't already
if not type -fq brew
  mise run install:homebrew
end

# Install software defined in Brewfile
brew bundle --global
