#!/usr/bin/env fish

function fedora-version
  grep VERSION_ID /etc/os-release | cut -d= -f2
end

if grep -q "TUXEDO InfinityBook Max 15 AMD Gen10" /sys/devices/virtual/dmi/id/product_name
  echo "detected device: pluto"

  if not type -fq tlp
    echo "installing tlp"

    echo "removing packages that conflict with TLP"
    sudo dnf remove power-profiles-daemon tuned tuned-ppd

    echo "installing tlp repository"
    curl -L -o /tmp/tlp-release.rpm https://repo.linrunner.de/fedora/tlp/repos/releases/tlp-release.fc(fedora-version).noarch.rpm
    sudo dnf install /tmp/tlp-release.rpm
    rm /tmp/tlp-release.rpm

    echo "installing tlp"
    sudo dnf install tlp tlp-pd
  end

  if not type -fq coolercontrold
    echo "installing CoolerControl"

    dnf copr list | grep -q codifryed/CoolerControl
      or sudo dnf copr enable codifryed/CoolerControl

    sudo dnf install coolercontrol
  end
end
