[dotfiles]
"~/.config/DankMaterialShell/*.json" = "packages/home.linux/.config/DankMaterialShell/*.json"
"~/.config/gamemode.ini" = "packages/home.linux/.config/gamemode.ini"
"~/.config/kitty/conf.d/*" = "packages/home.linux/.config/kitty/conf.d/*"
"~/.config/matugen" = "packages/home.linux/.config/matugen"
"~/.config/niri/*" = "packages/home.linux/.config/niri/*"
"~/.config/solaar" = "packages/home.linux/.config/solaar"
"~/.config/systemd/user/*" = "packages/home.linux/.config/systemd/user/*"
"~/.config/xremap" = "packages/home.linux/.config/xremap"
"~/.local/bin/*" = "packages/home.linux/.local/bin/*"
"~/.local/share/actions-for-nautilus" = "packages/home.linux/.local/share/actions-for-nautilus"
"~/.local/share/nautilus/scripts" = "packages/home.linux/.local/share/nautilus/scripts"
"~/.local/share/vicinae/scripts" = "packages/home.linux/.local/share/vicinae/scripts"
"~/Templates" = "packages/home.linux/Templates"
