[dotfiles]
"~/.config/DankMaterialShell/*.json" = "config/DankMaterialShell/*.json"
"~/.config/gamemode.ini" = "config/gamemode.ini"
"~/.config/matugen" = "config/matugen"
"~/.config/niri/*" = "config/niri/*"
"~/.config/solaar" = "config/solaar"
"~/.config/systemd/user/*" = "config/systemd/user/*"
"~/.config/xremap" = "config/xremap"
"~/.local/bin/*" = "linux/bin/*"
"~/.local/share/actions-for-nautilus" = "config/actions-for-nautilus"
"~/.local/share/nautilus/scripts" = "config/nautilus/scripts"
"~/.local/share/vicinae/scripts" = "config/vicinae/scripts"
"~/Templates" = "config/nautilus/templates"
