[bootstrap.packages]
# Get a newer Bash version needed for running some scripts
"brew-cask:1password-cli" = "latest"
"brew:bash" = "latest"
# "brew:widen/brew/slipway" = "latest"

# [bootstrap.brew.taps]
# "widen/brew" = "git@github.com:Widen/brew"

[bootstrap.macos.launchd.agents.pitchfork]
program = "~/.local/bin/mise"
args = ["exec", "--env", "widen", "--", "pitchfork", "supervisor", "run", "--boot"]
stdout_path = "~/Library/Logs/pitchfork.log"
stderr_path = "~/Library/Logs/pitchfork.err.log"
run_at_load = true
