[dotfiles]
"~/.Brewfile" = "config/.Brewfile"
"~/Library/Application Support/k9s/skins/transparent.yaml" = "config/k9s/skins/transparent.yaml"
"~/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/*" = "config/alfred/workflows/*"
"~/Library/Application Support/SwiftBar/plugins/*" = "config/swiftbar/plugins/*"

[bootstrap.packages]
"brew-cask:block-goose" = "latest"
"brew-cask:font-hurmit-nerd-font" = "latest"
"brew-cask:font-symbols-only-nerd-font" = "latest"
"brew-cask:jordanbaird-ice" = "latest"
"brew-cask:middleclick" = "latest"
"brew-cask:swiftbar" = "latest"
"brew:btop" = "latest"
"brew:colima" = "latest"
"brew:coreutils" = "latest"
"brew:docker" = "latest"
"brew:docker-buildx" = "latest"
"brew:docker-compose" = "latest"
"brew:exiftool" = "latest"
"brew:fish" = "latest"
"brew:gifsicle" = "latest"
"brew:gnu-sed" = "latest"
"brew:gnu-tar" = "latest"
"brew:gnutls" = "latest"
"brew:imagemagick" = "latest"
"brew:media-info" = "latest"
"brew:parallel" = "latest"
"brew:qpdf" = "latest"
"brew:rename" = "latest"
"brew:terminal-notifier" = "latest"
"brew:watch" = "latest"
"brew:zenity" = "latest"
