[dotfiles]
"~/.cargo/config.toml" = "config/cargo/config.toml"
"~/.config/atuin" = "config/atuin"
"~/.config/broot/*" = "config/broot/*"
"~/.config/fish/**/*.fish" = "config/fish/**/*.fish"
"~/.config/gh/config.yml" = "config/gh/config.yml"
"~/.config/git" = "config/git"
"~/.config/k9s/skins/transparent.yaml" = "config/k9s/skins/transparent.yaml"
"~/.config/kitty/*.conf" = "config/kitty/*.conf"
"~/.config/mise" = "config/mise"
"~/.config/organize" = "config/organize"
"~/.config/pitchfork/config.toml" = "config/pitchfork/config.toml"
"~/.config/tio" = "config/tio"
"~/.config/zed/*.json" = "config/zed/*.json"
"~/.editorconfig" = ".editorconfig"

[settings]
dotfiles.default_mode = "symlink"
experimental = true

[tools]
ripgrep = "latest"
yq = "latest"

[tasks.bootstrap]
depends = ["configure:*"]

[tasks."install:homebrew"]
file = "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"

[tasks."install:rustup"]
file = "https://static.rust-lang.org/rustup/rustup-init.sh"
