[dotfiles]
"~/.cargo/config.toml" = "config/cargo/config.toml"
"~/.config/atuin" = "config/atuin"
"~/.config/broot/*" = "config/broot/*"
"~/.config/fish/**/*.fish" = "config/fish/**/*.fish"
"~/.config/gh/config.yml" = "config/gh/config.yml"
"~/.config/git" = "config/git"
"~/.config/k9s/skins/transparent.yaml" = "config/k9s/skins/transparent.yaml"
"~/.config/kitty/*.conf" = "config/kitty/*.conf"
"~/.config/mise" = "config/mise"
"~/.config/organize" = "config/organize"
"~/.config/tio" = "config/tio"
"~/.config/zed/*.json" = "config/zed/*.json"
"~/.editorconfig" = ".editorconfig"

[bootstrap.packages]
"dnf:distrobox" = "latest"
"dnf:firefox" = "latest"
"dnf:fish" = "latest"
"dnf:flac" = "latest"
"dnf:gnome-network-displays" = "latest"
"dnf:google-droid-fonts-all" = "latest"
"dnf:ImageMagick-heic" = "latest"
"dnf:kitty" = "latest"
"dnf:libva-utils" = "latest"
"dnf:lsof" = "latest"
"dnf:make" = "latest"
"dnf:msedit" = "latest"
"dnf:NetworkManager-tui" = "latest"
"dnf:nvtop" = "latest"
"dnf:pcaro-hermit-fonts" = "latest"
"dnf:perl-Image-ExifTool" = "latest"
"dnf:powertop" = "latest"
"dnf:prename" = "latest"
"dnf:rclone" = "latest"
"dnf:seafile-client" = "latest"
"dnf:solaar" = "latest"
"dnf:sox" = "latest"
"dnf:speech-dispatcher" = "latest"
"dnf:speech-dispatcher-utils" = "latest"
"dnf:tio" = "latest"
"dnf:vdpauinfo" = "latest"
"dnf:wireguard-tools" = "latest"
"dnf:wl-clipboard" = "latest"
"dnf:xdg-terminal-exec" = "latest"
"dnf:ydotool" = "latest"

[bootstrap.macos.defaults."com.apple.desktopservices"]
DSDontWriteNetworkStores = true

[bootstrap.macos.defaults."com.apple.finder"]
_FXShowPosixPathInTitle = true
_FXSortFoldersFirst = true
FXEnableExtensionChangeWarning = false
ShowPathbar = true

[bootstrap.macos.defaults.NSGlobalDomain]
AppleInterfaceStyle = "Dark"
AppleShowAllExtensions = true

[settings]
dotfiles.default_mode = "symlink"
experimental = true

[tools]
ripgrep = "latest"
yq = "latest"

[tools."aqua:fish-shell/fish-shell"]
version = "latest"
os = ["linux"]

[tasks.bootstrap]
depends = ["configure:*"]

[tasks."install:homebrew"]
file = "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"

[tasks."install:rustup"]
file = "https://static.rust-lang.org/rustup/rustup-init.sh"
