[dotfiles]
"~/.Brewfile" = "packages/home.darwin/.Brewfile"
"~/.config/kitty/conf.d/*" = "packages/home.darwin/.config/kitty/conf.d/*"
"~/Library/Application Support/k9s/skins/transparent.yaml" = "packages/home/.config/k9s/skins/transparent.yaml"
"~/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/*" = "packages/home.darwin/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/*"
"~/Library/Application Support/SwiftBar/plugins/*" = "packages/home.darwin/Library/Application Support/SwiftBar/plugins/*"
