[bootstrap.packages]
"dnf:ImageMagick-heic" = "latest"
"dnf:NetworkManager-tui" = "latest"
"dnf:distrobox" = "latest"
"dnf:exiftool" = "latest"
"dnf:firefox" = "latest"
"dnf:fish" = "latest"
"dnf:flac" = "latest"
"dnf:gnome-network-displays" = "latest"
"dnf:google-droid-fonts-all" = "latest"
"dnf:kitty" = "latest"
"dnf:libva-utils" = "latest"
"dnf:lsof" = "latest"
"dnf:make" = "latest"
"dnf:msedit" = "latest"
"dnf:nvtop" = "latest"
"dnf:pcaro-hermit-fonts" = "latest"
"dnf:powertop" = "latest"
"dnf:prename" = "latest"
"dnf:rclone" = "latest"
"dnf:seafile-client" = "latest"
"dnf:solaar" = "latest"
"dnf:sox" = "latest"
"dnf:speech-dispatcher" = "latest"
"dnf:speech-dispatcher-utils" = "latest"
"dnf:tio" = "latest"
"dnf:vdpauinfo" = "latest"
"dnf:wireguard-tools" = "latest"
"dnf:wl-clipboard" = "latest"
"dnf:xdg-terminal-exec" = "latest"
"dnf:ydotool" = "latest"
