schema-version = "1.10.0"

[install]
devenv.pkg-group = "devenv"
devenv.pkg-path = "devenv"
exiftool.outputs = "all"
exiftool.pkg-path = "exiftool"
flac.outputs = "all"
flac.pkg-path = "flac"
hurmit.pkg-path = "nerd-fonts.hurmit"
kubernetes-helm.pkg-path = "kubernetes-helm"
libinput-gestures.pkg-path = "libinput-gestures"
libinput-gestures.systems = ["aarch64-linux", "x86_64-linux"]
mkvtoolnix-cli.pkg-path = "mkvtoolnix-cli"
numbat.pkg-path = "numbat"
nvtop.pkg-path = "nvtop"
pdfcpu.pkg-path = "pdfcpu"
qpdf.outputs = "all"
qpdf.pkg-path = "qpdf"
sox.outputs = "all"
sox.pkg-path = "sox"
tio.pkg-path = "tio"
wev.pkg-path = "wev"
wev.systems = ["x86_64-linux"]
xdg-terminal-exec.pkg-path = "xdg-terminal-exec"
xdg-terminal-exec.systems = ["x86_64-linux"]

[options]
activate.mode = "run"
allow.unfree = true
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-linux"]
