# https://espanso.org/docs/

matches:
  - trigger: "me@"
    replace: "me@stephencoakley.com"

  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"
