[dotfiles]
"~/.config/DankMaterialShell/*.json" = "../config/DankMaterialShell/*.json"
"~/.config/gamemode.ini" = "../config/gamemode.ini"
"~/.config/matugen" = "../config/matugen"
"~/.config/niri/*" = "../config/niri/*"
"~/.config/solaar" = "../config/solaar"
"~/.config/systemd/user/*" = "../config/systemd/user/*"
"~/.config/xdg-terminals.list" = "../config/xdg-terminals.list"
"~/.config/xremap" = "../config/xremap"
"~/.local/bin/*" = "../bin/linux/*"
"~/.local/share/actions-for-nautilus" = "../config/actions-for-nautilus"
"~/.local/share/nautilus/scripts" = "../config/nautilus/scripts"
"~/.local/share/vicinae/scripts" = "../config/vicinae/scripts"
"~/Templates" = "../config/nautilus/templates"

[bootstrap.packages]
"dnf:alsa-tools" = "latest"
"dnf:bleachbit" = "latest"
"dnf:distrobox" = "latest"
"dnf:firefox" = "latest"
"dnf:fish" = "latest"
"dnf:flac" = "latest"
"dnf:gnome-network-displays" = "latest"
"dnf:google-droid-fonts-all" = "latest"
"dnf:ImageMagick-heic" = "latest"
"dnf:kitty" = "latest"
"dnf:libva-utils" = "latest"
"dnf:lsof" = "latest"
"dnf:make" = "latest"
"dnf:mkvtoolnix" = "latest"
"dnf:msedit" = "latest"
"dnf:NetworkManager-tui" = "latest"
"dnf:nvtop" = "latest"
"dnf:pcaro-hermit-fonts" = "latest"
"dnf:perl-Image-ExifTool" = "latest"
"dnf:powertop" = "latest"
"dnf:prename" = "latest"
"dnf:rclone" = "latest"
"dnf:seafile-client" = "latest"
"dnf:solaar" = "latest"
"dnf:sox" = "latest"
"dnf:speech-dispatcher" = "latest"
"dnf:speech-dispatcher-utils" = "latest"
"dnf:tesseract" = "latest"
"dnf:tio" = "latest"
"dnf:vdpauinfo" = "latest"
"dnf:wev" = "latest"
"dnf:wireguard-tools" = "latest"
"dnf:wl-clipboard" = "latest"
"dnf:xdg-terminal-exec" = "latest"
"dnf:ydotool" = "latest"
"dnf:zed" = "latest"
"flatpak:ai.jan.Jan" = "latest"
"flatpak:app.drey.EarTag" = "latest"
"flatpak:be.alexandervanhee.gradia" = "latest"
"flatpak:ca.littlesvr.asunder" = "latest"
"flatpak:com.bitwarden.desktop" = "latest"
"flatpak:com.github.d4nj1.tlpui" = "latest"
"flatpak:com.github.jeromerobert.pdfarranger" = "latest"
"flatpak:com.github.neithern.g4music" = "latest"
"flatpak:com.github.rafostar.Clapper" = "latest"
"flatpak:com.github.tchx84.Flatseal" = "latest"
"flatpak:com.github.wwmm.easyeffects" = "latest"
"flatpak:com.jetbrains.DataGrip" = "latest"
"flatpak:com.makemkv.MakeMKV" = "latest"
"flatpak:com.moonlight_stream.Moonlight" = "latest"
"flatpak:com.ranfdev.DistroShelf" = "latest"
"flatpak:com.saivert.pwvucontrol" = "latest"
"flatpak:de.hohnstaedt.xca" = "latest"
"flatpak:es.danirod.Cartero" = "latest"
"flatpak:fm.reaper.Reaper" = "latest"
"flatpak:fr.handbrake.ghb" = "latest"
"flatpak:io.github.dimtpap.coppwr" = "latest"
"flatpak:io.github.dweymouth.supersonic" = "latest"
"flatpak:io.github.flattool.Ignition" = "latest"
"flatpak:io.github.flattool.Warehouse" = "latest"
"flatpak:io.github.kolunmi.Bazaar" = "latest"
"flatpak:io.github.Qalculate" = "latest"
"flatpak:io.github.qwersyk.Newelle" = "latest"
"flatpak:io.github.tanaybhomia.Whisp" = "latest"
"flatpak:io.gitlab.adhami3310.Impression" = "latest"
"flatpak:io.gitlab.liferooter.TextPieces" = "latest"
"flatpak:io.missioncenter.MissionCenter" = "latest"
"flatpak:io.qt.qdbusviewer" = "latest"
"flatpak:md.obsidian.Obsidian" = "latest"
"flatpak:me.iepure.devtoolbox" = "latest"
"flatpak:net.filebot.FileBot" = "latest"
"flatpak:net.scribus.Scribus" = "latest"
"flatpak:net.trowell.typesetter" = "latest"
"flatpak:nl.andreasknoben.Laser" = "latest"
"flatpak:org.ardour.Ardour" = "latest"
"flatpak:org.audacityteam.Audacity" = "latest"
"flatpak:org.gimp.GIMP" = "latest"
"flatpak:org.gnome.meld" = "latest"
"flatpak:org.gustavoperedo.FontDownloader" = "latest"
"flatpak:org.keepassxc.KeePassXC" = "latest"
"flatpak:org.localsend.localsend_app" = "latest"
"flatpak:org.musicbrainz.Picard" = "latest"
"flatpak:org.nickvision.tubeconverter" = "latest"
"flatpak:org.onlyoffice.desktopeditors" = "latest"

[bootstrap.users.stephen]
group = "stephen"
# allow unprivileged uinput use
groups = ["input"]

[bootstrap.directories."/etc/mise"]
owner = "root"
group = "root"
mode = "0755"

# detect system info and set machine-specific mise env
[bootstrap.files."/etc/mise/miserc.toml"]
owner = "root"
group = "root"
template = true
content = """
env = [
{% if "TUXEDO" in read_file(path="/sys/devices/virtual/dmi/id/chassis_vendor") %}
    "tuxedo",
{% endif %}
{% if "TUXEDO InfinityBook Max 15 AMD Gen10" in read_file(path="/sys/devices/virtual/dmi/id/product_name") %}
    "pluto",
{% endif %}
]
"""

# configure the sg module to load automatically
[bootstrap.files."/etc/modules-load.d/99-sg.conf"]
content = "sg\n"

[bootstrap.linux.systemd.units.keepassxc]
description = "KeePassXC system tray service"
wants = ["graphical-session.target"]
after = ["graphical-session.target"]
exec_start = "flatpak run org.keepassxc.KeePassXC --minimized"
wanted_by = ["graphical-session.target"]

[bootstrap.linux.systemd.units.kitty]
description = "Kitty terminal (single-instance, hidden)"
wants = ["graphical-session.target"]
after = ["graphical-session.target"]
exec_start = "/usr/bin/kitty --start-as=hidden --single-instance"
restart = "on-failure"
restart_sec = "2s"
wanted_by = ["graphical-session.target"]
