[dotfiles]
"~/.local/bin/idea" = "../bin/idea"
"~/.Brewfile" = "../config/.Brewfile"
"~/Library/Application Support/k9s/skins/transparent.yaml" = "../config/k9s/skins/transparent.yaml"
"~/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/*" = "../config/alfred/workflows/*"
"~/Library/Application Support/SwiftBar/plugins/*" = "../config/swiftbar/plugins/*"

# detect system info and set machine-specific mise env
[dotfiles."~/.miserc.toml/env"]
template = "tera"
block = """
env = [
{% if "MacBookPro18,2" in exec(command="system_profiler SPHardwareDataType") %}
    "widen",
{% endif %}
]
"""

[bootstrap.packages]
"brew-cask:font-hurmit-nerd-font" = "latest"
"brew-cask:font-symbols-only-nerd-font" = "latest"
"brew-cask:jordanbaird-ice" = "latest"
"brew-cask:middleclick" = "latest"
"brew-cask:swiftbar" = "latest"
"brew:btop" = "latest"
"brew:colima" = "latest"
"brew:coreutils" = "latest"
"brew:docker" = "latest"
"brew:docker-buildx" = "latest"
"brew:docker-compose" = "latest"
"brew:exiftool" = "latest"
"brew:fish" = "latest"
"brew:gifsicle" = "latest"
"brew:gnu-sed" = "latest"
"brew:gnu-tar" = "latest"
"brew:gnutls" = "latest"
"brew:imagemagick" = "latest"
"brew:media-info" = "latest"
"brew:parallel" = "latest"
"brew:qpdf" = "latest"
"brew:rename" = "latest"
"brew:terminal-notifier" = "latest"
"brew:watch" = "latest"
"brew:zenity" = "latest"

[bootstrap.macos.launchd.agents.atuin]
program = "~/.local/bin/mise"
args = ["exec", "--", "atuin", "daemon", "start"]
stdout_path = "~/Library/Logs/atuin-daemon.log"
stderr_path = "~/Library/Logs/atuin-daemon.err.log"
run_at_load = true

[bootstrap.macos.defaults."com.apple.desktopservices"]
DSDontWriteNetworkStores = true

[bootstrap.macos.defaults."com.apple.finder"]
_FXShowPosixPathInTitle = true
_FXSortFoldersFirst = true
FXEnableExtensionChangeWarning = false
ShowPathbar = true

[bootstrap.macos.defaults.NSGlobalDomain]
AppleInterfaceStyle = "Dark"
AppleShowAllExtensions = true
