[dotfiles]
"~/.config/DankMaterialShell/*.json" = "../config/DankMaterialShell/*.json"
"~/.config/niri/machine-specific.kdl".content = '''
environment {
    // Prefer integrated GPU in Vulkan calls.
    MESA_VK_DEVICE_SELECT "1002:150e"
}

input {
    touchpad {
        tap
    }
}

binds {
    XF86KbdLightOnOff {
        spawn "~/.config/niri/scripts/toggle-kbd-backlight.fish";
    }
}

debug {
    force-disable-connectors-on-resume

    render-drm-device "/dev/dri/by-path/pci-0000:67:00.0-render"
    ignore-drm-device "/dev/dri/by-path/pci-0000:65:00.0-render"
}
'''

[bootstrap.directories]
"/etc/libinput" = {
    owner = "root",
    group = "root",
    mode = "0755",
}
"/usr/local/bin" = {
    owner = "root",
    group = "root",
    mode = "0755",
}

[bootstrap.files]
"/etc/libinput/local-overrides.quirks".source = "../system/pluto/etc/libinput/local-overrides.quirks"
"/etc/modprobe.d/pluto-nvidia.conf".source = "../system/pluto/etc/modprobe.d/pluto-nvidia.conf"
"/etc/systemd/system/tuxedo-charging-profile.service".source = "../system/pluto/etc/systemd/system/tuxedo-charging-profile.service"
"/etc/systemd/system/tuxedo-charging-profile.timer".source = "../system/pluto/etc/systemd/system/tuxedo-charging-profile.timer"
"/etc/udev/rules.d/60-tuxedo-kbd-leds-uaccess.rules".source = "../system/pluto/etc/udev/rules.d/60-tuxedo-kbd-leds-uaccess.rules"
"/usr/local/bin/tuxedo-charging-profile" = {
    source = "../system/pluto/bin/tuxedo-charging-profile",
    mode = "0755",
}

[bootstrap.linux.systemd.units.easy-effects-profile]
type = "oneshot"
exec_start = "~/.local/bin/easy-effects-timer"

[bootstrap.linux.systemd.units.easy-effects-profile-timer]
on_boot_sec = "120"
on_unit_active_sec = "10"
unit = "easy-effects-profile"
