" Basic settings.
set encoding=utf8
set nocompatible
filetype plugin indent on
set history=1000
set undolevels=1000
set title
set visualbell
set noerrorbells
set backspace=indent,eol,start

" Enable syntax highlighting and set theme.
set t_Co=256
set background=dark
syntax enable
colorscheme gruvbox
highlight Normal ctermbg=none
highlight ColorColumn ctermbg=darkgray

" Customize interface.
set colorcolumn=120
set cursorline      " Highlight the cursor line
set fillchars+=vert:│
set hidden
set laststatus=2
set lazyredraw
set showmatch       " Highlight matching parenthesis

" Display settings for lines and wrapping.
set number          " Show line numbers
set wrap            " Turn on soft wrapping
set linebreak
set nolist
set breakindent     " Line up indentation when soft wrapping

" Set default indentation settings.
set shiftwidth=4
set softtabstop=4
set tabstop=4
set shiftround
set expandtab
set smarttab        " Insert tabs on the start of a line according to shiftwidth, not tabstop
set autoindent
set copyindent

" Search settings
set ignorecase      " Ignore case when searching
set smartcase       " Ignore case if search pattern is all lowercase, case-sensitive otherwise
set hlsearch        " Highlight search terms
set incsearch       " Show search matches as you type

" Cool command completion stuff
set wildmenu
set wildmode=list:longest,full

" Enable mouse wheel and selection.
set mouse=a
set selectmode=mouse,key
set keymodel=startsel

" Dealing with files
set nobackup
set noswapfile
autocmd BufWritePre * :%s/\s\+$//e " trim trailing whitespace
autocmd BufNewFile,BufRead *.json set ft=javascript

" Code folding
set foldmethod=indent
set foldnestmax=10
set nofoldenable
set foldlevel=1

" Turn on automatic spell checking
set spell spelllang=en_us


" File keyboard shortcuts.
nnoremap <C-s> :w<CR>
inoremap <C-s> <C-o>:w<CR>
nnoremap <C-q> :q<CR>
inoremap <C-q> <C-o>:q<CR>
nnoremap <F4> :bd<CR>
inoremap <F4> <C-o>:bd<CR>
" Reload config!
nnoremap <F12> :so $MYVIMRC<CR>

" Text and buffer navigation
nnoremap <C-end> G
vnoremap <C-end> G
nnoremap <C-home> gg
vnoremap <C-home> gg
nnoremap <C-tab> :bnext<CR>

" Use familiar shortcuts for copy and paste.
set clipboard=unnamed
nnoremap <C-c> "+yy
vnoremap <C-c> "+yy
nnoremap <C-x> "+dd
vnoremap <C-x> "+dd
nnoremap <C-v> "+gP
inoremap <C-v> <C-\><C-o>"+gP

" Undo and redo.
nnoremap <C-z> u
inoremap <C-z> <C-\><C-o>u
nnoremap <C-y> :redo<CR>
inoremap <C-y> <C-\><C-o>:redo<CR>

" Indentation shortcuts
inoremap <tab> <C-o>><CR>
vnoremap <tab> >
inoremap <S-tab> <C-o><<CR>
vnoremap <S-tab> <

" Move lines up and down with Ctrl-up and Ctrl-down
nnoremap <C-up> :m-2<CR>==
inoremap <C-up> <C-o>:m-2<CR>
vnoremap <C-up> :m-2<CR>gv=gv
nnoremap <C-down> :m+<CR>==
inoremap <C-down> <C-o>:m+<CR>
vnoremap <C-down> :m'>+<CR>gv=gv
