[settings]
experimental = true

[tools]
atuin = "latest"
edit = "latest"
eza = "latest"
gh = "latest"
"github:Nukesor/pueue" = "latest"
"github:canop/broot" = "latest"
"github:complexlogic/rsgain" = "latest"
"github:ip7z/7zip" = "latest"
"github:skim-rs/skim" = "latest"
jq = "latest"
k9s = "latest"
kubectl = "latest"
regctl = "latest"
tokei = "latest"
yq = "latest"

[tools."github:benibela/xidel"]
version = "0.9.8"
os = ["linux/x64"]
platforms.linux-x64.asset_pattern = "xidel-*.linux64.tar.gz"
