- name: Add myself to "input" group to allow unprivileged uinput tools
  become: true
  ansible.builtin.user:
    name: stephen
    groups: input
    append: true

- name: Fedora configuration
  when: ansible_facts['pkg_mgr'] == 'dnf5'
  import_tasks: fedora.yml

- name: Install Flatpak apps
  import_tasks: flatpak.yml

- name: Configure Nautilus
  import_role:
    name: nautilus
