- name: Install Zed for Linux using script
  when: ansible_facts['system'] == "Linux"
  ansible.builtin.command:
    cmd: "curl -f https://zed.dev/install.sh | sh"
    creates: "~/.local/bin/zed"

- name: Install Zed for macOS using Homebrew
  when: ansible_facts['os_family'] == "Darwin"
  community.general.homebrew_cask:
    name: zed
    state: present
