#!/usr/bin/env fish

echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | while read --line filename
  mise exec -- ocrmypdf --quiet --skip-text $filename $filename
end | zenity --progress --pulsate --auto-close
