- name: Copy the /usr directory
  become: true
  ansible.builtin.copy:
    src: usr
    dest: /

- name: Copy the /etc directory
  become: true
  ansible.builtin.copy:
    src: etc
    dest: /

- name: Enable charging profile timer
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: tuxedo-charging-profile.timer
    state: started
    enabled: true

- name: Reload udev rules
  become: true
  ansible.builtin.command:
    cmd: udevadm control --reload

- name: Trigger udev rules
  become: true
  ansible.builtin.command:
    cmd: udevadm trigger -v -s leds

- name: Install CC plugin
  import_tasks: cc-plugin.yml
