#!/usr/bin/env fish

for copr in ulysg/xwayland-satellite blakegardner/xremap yalter/niri avengemedia/dms
  dnf copr list | grep -q $copr
    or sudo dnf copr enable -y $copr
end

# Might already have super old quickshell, need to upgrade to something newer.
sudo dnf install -y --allowerasing dms niri nodejs quickshell-git vicinae wayland-utils xremap-niri
sudo dnf remove -y mako waybar

systemctl enable --user dms.service
systemctl enable --user vicinae.service
