#!/usr/bin/env fish

set -l packages home

# Determine extra stow packages to install
if status build-info | string match -q '*apple*'
  set -a packages home.darwin
else if status build-info | string match -q '*linux*'
  set -a packages home.linux
end

# Set executable bit on binaries that might be missing it
chmod +x home.linux/.local/bin/*

# Unfold any directories containing .no-stow-folding
find $packages -type f -name .no-stow-folding -exec sh -c 'mkdir -pv ~/$(dirname "$1" | cut -d/ -f2-)' sh '{}' ';'

# Run stow to make symlinks
stow --stow --dir="$PWD/packages" $packages
