#!/usr/bin/env fish

set -l packages packages/home

# Determine extra stow packages to install
if status build-info | string match -q '*apple*'
  set -a packages packages/home.darwin
else if status build-info | string match -q '*linux*'
  set -a packages packages/home.linux
end

echo stow --restow --dir="$PWD/packages" $packages
