layerrules = true
kill_bind = "ctrl+shift+alt, h"

[windows]
scale = 8.5
workspaces_per_row = 5
strip_html_from_workspace_title = true

[windows.overview.open]
key = "super"

[windows.overview.navigate]
forward = "tab"

[windows.overview.navigate.reverse]
mod = "shift"

[windows.overview.other]
filter_by = []
hide_filtered = false

[windows.switch.open]
modifier = "alt"

[windows.switch.navigate]
forward = "tab"

[windows.switch.navigate.reverse]
mod = "shift"

[windows.switch.other]
filter_by = []
hide_filtered = true
